function BU () {
    display.clear()
    basic.pause(200)
    display.setPixelColor(3, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(4, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(11, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(12, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(19, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(20, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(24, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(27, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(28, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(31, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(32, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(33, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(35, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(36, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(38, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(39, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(41, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(42, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(43, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(44, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(45, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(46, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(50, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(51, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(52, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(53, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(59, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(60, neopixel.colors(NeoPixelColors.Blue))
    display.show()
}
input.onButtonPressed(Button.A, function () {
    basic.showIcon(IconNames.Silly)
})
function GR () {
    display.clear()
    basic.pause(200)
    display.setPixelColor(3, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(4, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(10, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(11, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(17, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(18, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(24, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(25, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(26, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(27, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(28, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(29, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(30, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(31, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(32, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(33, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(34, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(35, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(36, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(37, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(38, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(39, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(41, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(42, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(50, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(51, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(59, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(60, neopixel.colors(NeoPixelColors.Green))
    display.show()
}
function GU () {
    display.clear()
    basic.pause(200)
    display.setPixelColor(3, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(4, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(11, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(12, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(19, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(20, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(24, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(27, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(28, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(31, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(32, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(33, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(35, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(36, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(38, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(39, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(41, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(42, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(43, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(44, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(45, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(46, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(50, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(51, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(52, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(53, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(59, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(60, neopixel.colors(NeoPixelColors.Green))
    display.show()
}
function testGup () {
    let X = 0
    let Y = 0
    GU()
    if (Y < 650 && Y > 400 && X > 700 && input.buttonIsPressed(Button.A)) {
        game.addScore(1)
        action = -1
    } else {
        action = -2
        game.gameOver()
    }
}
function GD () {
    display.clear()
    basic.pause(200)
    display.setPixelColor(3, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(4, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(10, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(11, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(12, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(13, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(17, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(18, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(19, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(20, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(21, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(22, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(24, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(25, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(27, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(28, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(30, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(31, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(32, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(35, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(36, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(39, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(43, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(44, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(51, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(52, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(59, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(60, neopixel.colors(NeoPixelColors.Green))
    display.show()
}
input.onButtonPressed(Button.B, function () {
    basic.showIcon(IconNames.Happy)
})
function BL () {
    display.clear()
    basic.pause(200)
    display.setPixelColor(3, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(4, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(12, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(13, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(21, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(22, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(24, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(25, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(26, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(27, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(28, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(29, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(30, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(31, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(32, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(33, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(34, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(35, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(36, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(37, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(38, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(39, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(45, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(46, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(52, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(53, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(59, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(60, neopixel.colors(NeoPixelColors.Blue))
    display.show()
}
function BD () {
    display.clear()
    basic.pause(200)
    display.setPixelColor(3, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(4, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(10, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(11, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(12, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(13, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(17, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(18, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(19, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(20, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(21, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(22, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(24, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(25, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(27, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(28, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(30, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(31, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(32, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(35, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(36, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(39, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(43, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(44, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(51, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(52, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(59, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(60, neopixel.colors(NeoPixelColors.Blue))
    display.show()
}
function BR () {
    display.clear()
    basic.pause(200)
    display.setPixelColor(3, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(4, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(10, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(11, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(17, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(18, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(24, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(25, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(26, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(27, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(28, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(29, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(30, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(31, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(32, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(33, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(34, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(35, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(36, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(37, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(38, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(39, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(41, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(42, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(50, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(51, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(59, neopixel.colors(NeoPixelColors.Blue))
    display.setPixelColor(60, neopixel.colors(NeoPixelColors.Blue))
    display.show()
}
function GL () {
    display.clear()
    basic.pause(200)
    display.setPixelColor(3, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(4, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(12, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(13, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(21, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(22, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(24, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(25, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(26, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(27, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(28, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(29, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(30, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(31, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(32, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(33, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(34, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(35, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(36, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(37, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(38, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(39, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(45, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(46, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(52, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(53, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(59, neopixel.colors(NeoPixelColors.Green))
    display.setPixelColor(60, neopixel.colors(NeoPixelColors.Green))
    display.show()
}
let action = 0
let display: neopixel.Strip = null
display = neopixel.create(DigitalPin.P2, 64, NeoPixelMode.RGB)
let range = display.range(0, 64)
action = -1
basic.showIcon(IconNames.Heart)
loops.everyInterval(60000, function () {
    GD()
    basic.pause(2000)
    BL()
    basic.pause(2000)
    GU()
    basic.pause(2000)
    BR()
    basic.pause(2000)
})
basic.forever(function () {
	
})
